web:
  listen_address: "0.0.0.0"
  listen_port: "8080"

kafka:
  brokers: "192.168.123.16:9092"
  topics: ["data_changes", "orders_create"]  # 修改此行以支持多个 topic
  group_id: "data_sync_group"
  message_timeout_ms: "5000"
  auto_offset_reset: "earliest"

database:
  dbname: "kafka_example"
  user: "buste"
  password: "passw0rd"
  host: "192.168.123.16"
  port: "5432"
