name: Rust

on:
  push:
    branches: [ "v*.*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            EXTENSION: .exe

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest' && matrix.target == 'x86_64-apple-darwin'
        run: |
          brew install llvm
          echo "::set-env name=CC::$(brew --prefix llvm)/bin/clang"
          echo "::set-env name=CXX::$(brew --prefix llvm)/bin/clang++"
          echo "::set-env name=PATH::$(brew --prefix llvm)/bin:$PATH"

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --verbose --release --target=${{ matrix.TARGET }}

      - name: Rename
        run: cp target/${{ matrix.TARGET }}/release/kafka_example${{ matrix.EXTENSION }} kafka_example-${{ matrix.TARGET }}${{ matrix.EXTENSION }}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: kafka_example-${{ matrix.TARGET }}${{ matrix.EXTENSION }}
          path: kafka_example-${{ matrix.TARGET }}${{ matrix.EXTENSION }}
